trigger: none

name: 'cust_segm_train_pipeline'
jobs:
  - job: 'cust_segm_pipeline_job'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - group: TestVars
#      - group: KeyVault
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
          architecture: 'x64'
      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'Install Requirements'
      - script: |
          python src/mlops/create-job.py
        displayName: 'Run AML Job'
        env:
          TENANT_ID: $(tenantid)
          SP_ID: $(spid)
          SP_VALUE: $(spvalue)
          AML_WORKSPACE_NAME: $(wsname)
          RESOURCE_GROUP: $(rg)
          SUBSCRIPTION_ID: $(subscriptionid)
